# Generated by Django 3.2.5 on 2021-07-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=10)),
                ('duration', models.PositiveSmallIntegerField()),
                ('tittle', models.CharField(max_length=10)),
                ('units', models.CharField(max_length=10)),
                ('stack', models.CharField(max_length=10)),
            ],
        ),
    ]
