# Generated by Django 3.2.5 on 2021-07-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=10)),
                ('price', models.PositiveSmallIntegerField()),
                ('days', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('months', models.CharField(max_length=10)),
            ],
        ),
    ]
